services:
  archits-website:
    container_name: archits-website-app
    image: ${DOCKERHUB_USERNAME}/archits-website:latest
    restart: unless-stopped
    expose:
      - "4000"
    networks:
      - archits-website-net

  nginx:
    image: nginx:alpine
    container_name: archits-website-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - archits-website
    networks:
      - archits-website-net
    command: >
      sh -c "
      echo 'server {
        listen 80;
        server_name archits.dev www.archits.dev;
        location / {
          proxy_pass http://archits-website:4000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade \$$http_upgrade;
          proxy_set_header Connection upgrade;
          proxy_set_header Host \$$host;
          proxy_set_header X-Real-IP \$$remote_addr;
          proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
          proxy_cache_bypass \$$http_upgrade;
        }
      }' > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "

networks:
  archits-website-net:
    name: archits-website-net
    driver: bridge
