services:
  archits-website:
    container_name: archits-website-app
    image: ${DOCKERHUB_USERNAME}/archits-website:latest
    restart: unless-stopped
    expose:
      - "4000"
    networks:
      - archits-website-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: archits-website-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      archits-website:
        condition: service_healthy
    networks:
      - archits-website-net
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  archits-website-net:
    name: archits-website-net
    driver: bridge

configs:
  nginx_config:
    external: true