FROM nginx:alpine

# copy config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# test-check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -f http://localhost/ || exit 1

EXPOSE 80 443