name: Deploy Archits to VPS

on:
  push:
    branches: [ main ]
 
jobs:

  deploy:

    name: Deploy to VPS
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/archits-website:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/archits-website:${{ github.sha }}
      
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |        
          cd archits-website
        
          # Arrêter seulement votre projet
          docker compose -p archits-website down
       
          # Récupérer la nouvelle image
          docker compose -p archits-website pull
       
          # Relancer avec la nouvelle image
          docker compose -p archits-website up -d
       
          # Vérifier le statut
          docker compose -p archits-website ps
          
          # Nettoyer les anciennes images
          docker image prune -f